NODES = [
    {"id": "intake", "label": "IntakeNormalizer", "kind": "deterministic",
     "phase": "1 Intake", "detail": "Resolves patient, loads policy, builds the fact sheet"},
    {"id": "verify", "label": "RequestVerifier", "kind": "agent",
     "phase": "1 Intake", "detail": "Reasons over the fact sheet, returns a typed verdict"},
    {"id": "adjudicate", "label": "Adjudicate", "kind": "deterministic",
     "phase": "1 Intake", "detail": "Turns the verdict into a branch, fails closed"},
    {"id": "close", "label": "CloseRejected", "kind": "gate",
     "phase": "1 Intake", "detail": "Records the rejection reason"},
    {"id": "accept", "label": "MarkVerified", "kind": "deterministic",
     "phase": "2 Match", "detail": "Advances the request to verified"},
    {"id": "eligibility", "label": "EligibilityResolver", "kind": "deterministic",
     "phase": "2 Match", "detail": "Expands compatible groups, filters on policy rules"},
    {"id": "rank", "label": "CohortRanker", "kind": "deterministic",
     "phase": "2 Match", "detail": "Scores on rest, fatigue, proximity and repeat history"},
    {"id": "compose", "label": "OutreachComposer", "kind": "agent",
     "phase": "3 Approve", "detail": "Drafts one message per language and channel"},
    {"id": "gate", "label": "AutonomyGate", "kind": "gate",
     "phase": "3 Approve", "detail": "Decides if this run is routine enough to send without waking anyone"},
    {"id": "dispatch", "label": "Dispatch", "kind": "deterministic",
     "phase": "4 Deliver", "detail": "Sends each donor their message and records delivery"},
]

EDGES = [
    {"source": "intake", "target": "verify"},
    {"source": "verify", "target": "adjudicate"},
    {"source": "adjudicate", "target": "accept", "label": "verified"},
    {"source": "adjudicate", "target": "close", "label": "rejected"},
    {"source": "accept", "target": "eligibility"},
    {"source": "eligibility", "target": "rank"},
    {"source": "rank", "target": "compose", "label": "cohort found"},
    {"source": "compose", "target": "gate"},
    {"source": "gate", "target": "dispatch", "label": "cleared to send"},
]
